### ISSUE TITLE
Use crowdsale contract from zeppelin with timestamps

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#227]
We are not using the crowdsale contracts from zeppelin because on the version 1.20 still uses block numbers, but on the next version it will be using timestamps, and our crowdsale its simple enough now to reuse some of their code. Once the next version is released we should use as much as we can from it.

**Comment by nberger** [comment]
After discussing with @AugustoL we decided not to use the crowdsale contracts from zeppelin because we can't reuse 100% of them due to slight differences (instead of 1 rate and endTime we have 2 rates and 2 endTimestamps, also we don't forwardFunds to a separate wallet on each `buyTokens` transaction, etc) and all the overrides we have to do make it less worth it. We would end with code that is less readable and maybe even exposed to more potential bugs.

Another factor is that our contracts are basically done by now and with a good level of testing so we wouldn't gain much in that regard.
