### ISSUE TITLE
Multiply all token rates x10

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#300]
Change all the token rates in test and contracts to match:
110 Lifs per ETH in presale.
100 Lifs per ETH in first week of TGE.
90 Lifs per ETH in the second week of TGE.

**Comment by kvakes** [comment]
I think the community has resolved this issue on its own. But just in case: it absolutely doesn't matter whether 1 ETH = 10 lifs or 100. It is completely ridiculous to say "Lif is too expensive because I could buy 100 [name of coin] for the same amount of ETH". It's like saying that USD is more expensive than Zimbabwean dollar, therefore it makes more sense to buy Zimbabwean dollars because you would get more of them.
